name: User Wallets CI

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/user-wallets/**
  pull_request:
    branches: "*"
    paths:
      - packages/user-wallets/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn workspace @mimic-fi/v3-user-wallets lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: REPORT_GAS=true yarn workspace @mimic-fi/v3-user-wallets test
      - name: Gas Report
        env:
          CC_SECRET: ${{ secrets.CODECHECKS_SECRET }}
        run: yarn workspace @mimic-fi/v3-user-wallets codechecks
